relative-ci/bundle-stats

src/components/metrics-table/index.jsx
src/config/metrics.js
src/utils/format.js
src/utils/metrics.js

- extract formatter and getter
- use constants for names

Refactor metrics config

---

package.json

This reverts commit 8c633b04213368311509bd56a2c476e0fad375a5.

Revert "chore(package): update webpack-dev-server to version 3.0.0"

---

packages/ui/src/layout/footer/footer.jsx
packages/ui/src/layout/footer/footer.module.css

fix: UI - Footer

---

packages/ui/src/ui/table-filters/table-filters.container.jsx
packages/ui/src/ui/table-filters/table-filters.jsx
packages/ui/src/ui/table-filters/table-filters.module.css

fix: UI - TableFilters - show dropdown on label click

---

README.md
packages/bundle-stats/README.md

- add main features
- add CI info

docs: Update READMEs

---

packages/html-templates/src/app/header/header.module.css
packages/html-templates/src/app/index.jsx
packages/html-templates/src/app/styles.css
packages/ui/src/components/summary/summary.module.css
packages/ui/src/css/default.css
packages/ui/src/layout/footer/footer.module.css
packages/ui/src/layout/header/header.module.css
packages/ui/src/layout/index.js
packages/ui/src/layout/sub-header/index.js
packages/ui/src/layout/sub-header/sub-header.jsx
packages/ui/src/layout/sub-header/sub-header.module.css
packages/ui/src/layout/sub-header/sub-header.stories.jsx
packages/ui/src/prototypes/bundle-page.module.css
packages/ui/src/prototypes/bundle-page.stories.jsx
packages/ui/src/prototypes/typography.md
packages/ui/src/prototypes/typography.module.css
packages/ui/src/prototypes/typography.stories.jsx
packages/ui/src/ui/box/box.module.css
packages/ui/src/ui/container/container.module.css
packages/web-compare/src/app/styles.css
packages/web-compare/src/pages/browsertime/index.jsx
packages/web-compare/src/pages/lighthouse/index.jsx
packages/web-compare/src/pages/lighthouse/styles.css
packages/web-compare/src/pages/webpack/index.jsx
packages/web-compare/src/pages/webpack/styles.css

- remove box-shadow effect
- fix summary borders
- invert colors for footer
- tweak font weight for large titles

tweak: Update layout styles

---

packages/ui/__mocks__/lighthouse.json
packages/utils/src/config/metrics.js
packages/utils/src/lighthouse/get-lighthouse-metrics.js

Update lighthouse report

---

README.md
packages/bundle-stats/README.md
packages/bundle-stats/bin/index.js
packages/bundle-stats/bin/run.js
packages/bundle-stats/package-lock.json
packages/bundle-stats/package.json
packages/bundle-stats/src/__tests__/__snapshots__/webpack-plugin.test.js.snap
packages/bundle-stats/src/__tests__/webpack-plugin.test.js
packages/bundle-stats/src/baseline.js
packages/bundle-stats/src/index.js
packages/bundle-stats/src/text.js
packages/bundle-stats/src/webpack-plugin.js
packages/bundle-stats/test/package/__snapshots__/webpack-plugin.test.js.snap
packages/bundle-stats/test/package/webpack-plugin.test.js

feat: Compare mode

---

README.md
packages/bundle-stats/README.md
packages/next-plugin/.eslintrc.js
packages/next-plugin/.gitignore
packages/next-plugin/.npmignore
packages/next-plugin/LICENSE.md
packages/next-plugin/README.md
packages/next-plugin/index.js
packages/next-plugin/jsconfig.json
packages/next-plugin/package-lock.json
packages/next-plugin/package.json

feat: next-plugin

---

packages/ui/src/ui/horizontal-bar-chart/horizontal-bar-chart.jsx
packages/ui/src/ui/horizontal-bar-chart/horizontal-bar-chart.module.css
packages/ui/src/ui/horizontal-bar-chart/horizontal-bar-chart.stories.jsx

fix(ui): HorizontalBarChart - fix label rendering

---

packages/ui/src/layout/footer/footer.jsx
packages/ui/src/layout/footer/footer.module.css

- add changelog, roadmap links
- fix layout styles

fix(ui): Footer - updates

---

packages/ui/src/components/summary/summary.jsx
packages/utils/src/config/index.js
packages/utils/src/config/metrics.js
packages/utils/src/jobs/__tests__/create-job.js
packages/utils/src/stats/__tests__/create.js
packages/utils/src/stats/create.js
packages/utils/src/transforms/__tests__/count-duplicated-packages-bundle-transform.js
packages/utils/src/transforms/count-duplicated-packages-bundle-transform.js
packages/utils/src/transforms/index.js
packages/utils/src/transforms/packages-modules-bundle-transform.js

Duplicated package count metric

---

packages/ui/src/components/duplicate-packages-warning/duplicate-packages-warning.jsx
packages/ui/src/components/duplicate-packages-warning/duplicate-packages-warning.module.css
packages/ui/src/components/duplicate-packages-warning/duplicate-packages-warning.stories.jsx

fix(ui): DuplicatePackageWarning - improve display

---

packages/ui/src/components/summary-item/summary-item.module.css
packages/ui/src/components/summary/summary.jsx
packages/ui/src/components/summary/summary.module.css

- increase font size for large variation
- update grid layout

fix(ui): Summary - update styles

---

packages/html-templates/build/storybook/__snapshots__/storyshots.test.js.snap
packages/html-templates/src/app/index.jsx
packages/ui/src/components/bundle-assets-totals-chart-bars/bundle-assets-totals-chart-bars.jsx
packages/ui/src/components/bundle-assets-totals-chart-bars/bundle-assets-totals-chart-bars.module.css
packages/ui/src/components/jobs-header/jobs-header.stories.jsx
packages/ui/src/components/summary-item/summary-item.jsx
packages/ui/src/components/summary-item/summary-item.module.css
packages/ui/src/components/summary-item/summary-item.stories.jsx
packages/ui/src/components/summary/summary.jsx
packages/ui/src/components/summary/summary.stories.jsx
packages/ui/src/prototypes/bundle-page.stories.jsx

Update summary item

---

packages/html-templates/build/storybook/__snapshots__/storyshots.test.js.snap
packages/ui/src/components/bundle-assets-totals-chart-bars/bundle-assets-totals-chart-bars.jsx
packages/ui/src/components/bundle-assets/bundle-assets.container.js
packages/ui/src/components/bundle-assets/bundle-assets.jsx
packages/ui/src/components/bundle-assets/bundle-assets.module.css
packages/ui/src/components/bundle-assets/bundle-assets.stories.jsx
packages/ui/src/components/bundle-chunk-modules/bundle-chunk-modules.container.js
packages/ui/src/components/bundle-chunk-modules/bundle-chunk-modules.jsx
packages/ui/src/components/bundle-chunk-modules/bundle-chunk-modules.stories.jsx
packages/ui/src/components/bundle-packages/bundle-packages.container.js
packages/ui/src/components/bundle-packages/bundle-packages.jsx
packages/ui/src/components/bundle-packages/bundle-packages.stories.jsx
packages/ui/src/components/duplicate-packages-warning/duplicate-packages-warning.jsx
packages/ui/src/components/jobs-header/jobs-header.jsx
packages/ui/src/components/metrics-table/metrics-table.jsx
packages/ui/src/components/summary-item/summary-item.jsx
packages/ui/src/hocs/with-filters.js
packages/ui/src/ui/alert/alert.jsx
packages/ui/src/ui/empty-set/empty-set.jsx
packages/ui/src/ui/empty-set/empty-set.module.css
packages/ui/src/ui/empty-set/empty-set.stories.jsx
packages/ui/src/ui/empty-set/index.js
packages/ui/src/ui/filters-dropdown/filters-dropdown.container.jsx
packages/ui/src/ui/icon/icon.jsx
packages/ui/src/ui/icon/icon.stories.jsx
packages/ui/src/ui/index.js
packages/ui/src/ui/table/table.jsx
packages/ui/src/ui/tooltip/tooltip.jsx

fix(ui): MetricsTable - add specific empty messages

---

packages/ui/src/components/bundle-assets-totals-chart-bars/bundle-assets-totals-chart-bars.module.css
packages/ui/src/components/bundle-assets/bundle-assets.module.css
packages/ui/src/components/bundle-chunk-modules/bundle-chunk-modules.module.css
packages/ui/src/components/bundle-modules/bundle-modules.module.css
packages/ui/src/components/bundle-packages/bundle-packages.module.css
packages/ui/src/components/chart/chart.module.css
packages/ui/src/components/job-meta/job-meta.module.css
packages/ui/src/components/job-name/job-name.module.css
packages/ui/src/components/jobs-header/jobs-header.module.css
packages/ui/src/components/metric/metric.module.css
packages/ui/src/components/metrics-table/metrics-table.module.css
packages/ui/src/components/summary-item/summary-item.module.css
packages/ui/src/components/summary/summary.module.css
packages/ui/src/css/variables.css
packages/ui/src/ui/alert/alert.module.css
packages/ui/src/ui/box/box.module.css
packages/ui/src/ui/container/container.module.css
packages/ui/src/ui/dropdown/dropdown.module.css
packages/ui/src/ui/filters-dropdown/filters-dropdown.module.css
packages/ui/src/ui/horizontal-bar-chart/horizontal-bar-chart.module.css
packages/ui/src/ui/loader/loader.module.css
packages/ui/src/ui/sort-dropdown/sort-dropdown.module.css
packages/ui/src/ui/table/table.module.css
packages/ui/src/ui/tabs/tabs.module.css
packages/ui/src/ui/tooltip/tooltip.module.css

Ui updates

---

packages/bundle-stats/src/webpack-plugin.js
packages/ui/src/components/jobs-header/jobs-header.jsx

Fix builtAt

---

packages/ui/src/components/bundle-assets/bundle-assets.jsx
packages/ui/src/components/bundle-assets/bundle-assets.module.css
packages/ui/src/components/bundle-chunk-modules/bundle-chunk-modules.jsx
packages/ui/src/components/bundle-chunk-modules/bundle-chunk-modules.module.css
packages/ui/src/components/bundle-packages/bundle-packages.jsx
packages/ui/src/components/bundle-packages/bundle-packages.module.css
packages/ui/src/components/index.js
packages/ui/src/components/run-label-sum/index.js
packages/ui/src/components/run-label-sum/run-label-sum.jsx
packages/ui/src/components/run-label-sum/run-label-sum.module.css
packages/ui/src/components/run-label-sum/run-label-sum.stories.jsx
packages/ui/src/ui/table/table.module.css

Run - render total / delta on header

---

packages/ui/src/components/summary-item/summary-item.module.css
packages/ui/src/components/summary/summary.jsx
packages/ui/src/components/summary/summary.module.css

fix(ui): Summary - update layout

---

packages/bundle-stats/src/webpack-plugin.js

fix(bundle-stats): WebpackPlugin - load the baseline correctly

---

packages/bundle-stats/README.md

Add section about using with create-react-app

---

packages/cli/bin/run.js
packages/cli/locales.json
packages/utils/locales.json
packages/utils/src/webpack/__tests__/validate.js
packages/utils/src/webpack/index.js
packages/utils/src/webpack/validate.js
packages/webpack-plugin/locales.json
packages/webpack-plugin/src/webpack-plugin.js

Validate sources

---

packages/utils/src/webpack/__tests__/utils-get-asset-name.js
packages/utils/src/webpack/__tests__/utils-get-module-name.js
packages/utils/src/webpack/utils.js

rel: https://github.com/relative-ci/bundle-stats/issues/626

Fix module/asset name

---

packages/utils/locales.json
packages/utils/package-lock.json
packages/utils/package.json
packages/utils/src/webpack/__tests__/validate.js
packages/utils/src/webpack/index.js
packages/utils/src/webpack/struct.js
packages/utils/src/webpack/validate.js

Validate the entire webpack stats structure
close: https://github.com/relative-ci/bundle-stats/issues/19

fix(utils): Validate webpack stats structure

---

packages/utils/src/webpack/extract/__tests__/assets.js
packages/utils/src/webpack/extract/assets.js

feat(utils): Ignore .LICENSE.txt by default

---

packages/webpack-plugin/src/webpack-plugin.js

rel: https://github.com/relative-ci/bundle-stats/issues/1104

Fix webpack 5 emit

---

packages/ui/src/app/app.jsx
packages/ui/src/app/app.module.css
packages/ui/src/component-links.js
packages/ui/src/components/bundle-modules/__snapshots__/bundle-modules.stories.storyshot
packages/ui/src/components/bundle-modules/bundle-modules.jsx
packages/ui/src/components/summary-item/__snapshots__/summary-item.stories.storyshot
packages/ui/src/components/summary-item/summary-item.jsx
packages/ui/src/components/summary-item/summary-item.module.css
packages/ui/src/components/summary-item/summary-item.stories.jsx
packages/ui/src/components/summary/__snapshots__/summary.stories.storyshot
packages/ui/src/components/summary/summary.jsx
packages/ui/src/components/summary/summary.module.css
packages/ui/src/components/summary/summary.stories.jsx
packages/ui/src/constants.js
packages/ui/src/css/default.css
packages/ui/src/css/variables.css
packages/ui/src/i18n.js
packages/ui/src/layout/box/__snapshots__/box.stories.storyshot
packages/ui/src/layout/box/box.jsx
packages/ui/src/layout/box/box.module.css
packages/ui/src/layout/box/box.stories.jsx
packages/ui/src/layout/flex-stack/__snapshots__/flex-stack.stories.storyshot
packages/ui/src/layout/flex-stack/flex-stack.module.css
packages/ui/src/layout/stack/__snapshots__/stack.stories.storyshot
packages/ui/src/ui/alert/__snapshots__/alert.stories.storyshot
packages/ui/src/ui/dropdown/dropdown.module.css

- show only generic metrics
- show section specific metrics
- fix tooltips
close: https://github.com/relative-ci/bundle-stats/issues/1219

UI: Update summary

---

packages/ui/src/components/bundle-packages/bundle-packages.container.js
packages/ui/src/components/bundle-packages/bundle-packages.jsx
packages/ui/src/components/bundle-packages/bundle-packages.module.css
packages/ui/src/ui/index.js
packages/ui/src/ui/popover/__snapshots__/popover.stories.storyshot
packages/ui/src/ui/popover/index.js
packages/ui/src/ui/popover/popover.jsx
packages/ui/src/ui/popover/popover.module.css
packages/ui/src/ui/popover/popover.stories.jsx

Enhance bundle packages

---

packages/ui/src/app/app.jsx
packages/ui/src/components/bundle-modules/bundle-modules.container.js
packages/ui/src/components/bundle-packages/bundle-packages.jsx
packages/utils/src/config/component-links.js
packages/utils/src/utils/component-links.js

close: https://github.com/relative-ci/bundle-stats/issues/1211

Link package to modules

---

packages/ui/src/components/bundle-assets-totals-chart-bars/__snapshots__/bundle-assets-totals-chart-bars.stories.storyshot
packages/ui/src/components/bundle-assets-totals-chart-bars/bundle-assets-totals-chart-bars.jsx
packages/ui/src/components/bundle-assets-totals-chart-bars/bundle-assets-totals-chart-bars.module.css

close: https://github.com/relative-ci/bundle-stats/issues/1212

fix(ui): BundleTotalsChartBars - link to assets component

---

packages/ui/src/components/asset-info/asset-info.jsx

close: https://github.com/relative-ci/bundle-stats/issues/1310

fix(ui): BundleAssets - prevent error when chunk id is not available

---

fixtures/job.baseline.json
fixtures/job.current.json
packages/ui/src/components/bundle-assets/bundle-assets.container.js
packages/ui/src/components/bundle-modules/bundle-modules.container.js
packages/ui/src/components/bundle-packages/bundle-packages.container.js
packages/ui/src/hocs/with-search.jsx
packages/utils/src/webpack/compare.js

close: https://github.com/relative-ci/bundle-stats/issues/1224

Improve filtering

---

packages/ui/src/components/bundle-modules/bundle-modules.jsx
packages/ui/src/components/bundle-modules/bundle-modules.module.css
packages/ui/src/components/bundle-packages/bundle-packages.jsx
packages/ui/src/components/index.js
packages/ui/src/components/module-info/__snapshots__/module-info.stories.storyshot
packages/ui/src/components/module-info/index.js
packages/ui/src/components/module-info/module-info.jsx
packages/ui/src/components/module-info/module-info.stories.jsx
packages/ui/src/hocs/with-search.jsx
packages/ui/src/ui/popover/__snapshots__/popover.stories.storyshot
packages/ui/src/ui/popover/popover.jsx
packages/utils/src/utils/component-links.js

close: https://github.com/relative-ci/bundle-stats/issues/596

BundleModules updates

---

packages/ui/src/components/asset-info/asset-info.jsx
packages/ui/src/components/asset-info/asset-info.module.css
packages/ui/src/components/bundle-modules/bundle-modules.jsx
packages/ui/src/components/bundle-packages/bundle-packages.jsx
packages/ui/src/components/module-info/__snapshots__/module-info.stories.storyshot
packages/ui/src/components/module-info/module-info.jsx
packages/ui/src/components/module-info/module-info.module.css
packages/ui/src/ui/file-name/__snapshots__/file-name.stories.storyshot
packages/ui/src/ui/file-name/file-name.jsx
packages/ui/src/ui/popover/popover.jsx
packages/ui/src/ui/popover/popover.module.css

close: https://github.com/relative-ci/bundle-stats/issues/1314
close: https://github.com/relative-ci/bundle-stats/issues/1316

enhance(ui): Popover - normalize styles and behaviour

---

packages/utils/src/webpack/filter.js

Rel: https://github.com/relative-ci/bundle-stats/pull/1421

fix(utils): Filter - skip only null and undefined

---

.circleci/config.yml
package.json
packages/cli-utils/.babelrc.js
packages/cli-utils/package.json
packages/cli/package.json
packages/gatsby-plugin/package.json
packages/html-templates/.babelrc.js
packages/next-plugin/package.json
packages/utils/package.json
packages/webpack-plugin/.babelrc.js
packages/webpack-plugin/package.json

build: Drop node v10 support

---

packages/ui/src/components/bundle-assets-totals-chart-bars/__snapshots__/bundle-assets-totals-chart-bars.stories.storyshot
packages/ui/src/components/bundle-assets/__snapshots__/bundle-assets.stories.storyshot
packages/ui/src/components/bundle-modules/__snapshots__/bundle-modules.stories.storyshot
packages/utils/src/constants.ts
packages/utils/src/jobs/__tests__/__snapshots__/create-job.js.snap
packages/utils/src/report/__tests__/__snapshots__/create.js.snap
packages/utils/src/webpack/extract/__tests__/modules-packages-duplicate.js
packages/utils/src/webpack/extract/__tests__/modules-packages.ts
packages/utils/src/webpack/extract/modules-packages-duplicate.js
packages/utils/src/webpack/extract/modules-packages.ts

Duplicate packages - count all the instances

---

packages/ui/src/components/bundle-modules/__snapshots__/bundle-modules.stories.storyshot
packages/ui/src/components/bundle-modules/bundle-modules.container.js
packages/ui/src/components/bundle-modules/bundle-modules.jsx
packages/ui/src/components/bundle-modules/bundle-modules.stories.jsx
packages/ui/src/i18n.js

Rel: https://github.com/relative-ci/bundle-stats/issues/1308

fix(ui): BundleModules - filter by chunkId before merging

---

packages/utils/src/webpack/__tests__/utils-get-asset-name.js
packages/utils/src/webpack/utils.js

close: https://github.com/relative-ci/bundle-stats/issues/1543

fix(utils): Assets - replace 5 char hashes

---

packages/utils/src/webpack/__tests__/utils-get-module-name.js
packages/utils/src/webpack/extract/__tests__/modules-packages.ts
packages/utils/src/webpack/extract/modules-packages.ts
packages/utils/src/webpack/utils.js

close: https://github.com/relative-ci/bundle-stats/issues/1551

test(utils): Add cases for getPackageMetaFromModulePath

---

packages/ui/__mocks__/webpack-stats.current.json
packages/ui/src/components/bundle-assets-totals-chart-bars/__snapshots__/bundle-assets-totals-chart-bars.stories.storyshot
packages/ui/src/components/bundle-assets-totals-table/__snapshots__/bundle-assets-totals-table.stories.storyshot
packages/ui/src/components/bundle-assets/__snapshots__/bundle-assets.stories.storyshot
packages/ui/src/components/bundle-packages/__snapshots__/bundle-packages.stories.storyshot
packages/ui/src/components/bundle-packages/bundle-packages.container.js
packages/ui/src/components/bundle-packages/bundle-packages.stories.jsx
packages/ui/src/components/summary/__snapshots__/summary.stories.storyshot

close: https://github.com/relative-ci/bundle-stats/issues/1308

Fix packages comparison

---

packages/ui/src/ui/dropdown/dropdown.jsx
packages/ui/src/ui/dropdown/dropdown.module.css
packages/ui/src/ui/filters/__snapshots__/filters.stories.storyshot
packages/ui/src/ui/filters/filters.container.jsx
packages/ui/src/ui/filters/filters.jsx
packages/ui/src/ui/filters/filters.module.css
packages/ui/src/ui/sort-dropdown/__snapshots__/sort-dropdown.stories.storyshot
packages/ui/src/ui/sort-dropdown/sort-dropdown.jsx
packages/ui/src/ui/sort-dropdown/sort-dropdown.module.css

- consistent spacing
- consistent active state
- consistent close behaviour
close: https://github.com/relative-ci/bundle-stats/issues/1222

fix(ui): Dropdown - consistent look & feel

---

packages/ui/src/components/bundle-modules/bundle-modules.container.js
packages/ui/src/components/bundle-modules/bundle-modules.jsx
packages/utils/src/config/component-links.js
packages/utils/src/utils/component-links.js
packages/utils/src/webpack/constants.js
packages/utils/src/webpack/extract/modules-packages.ts

close: https://github.com/relative-ci/bundle-stats/issues/1321

Module source filters

---

packages/utils/src/utils/component-links.js

close: https://github.com/relative-ci/bundle-stats/issues/1580

utils: Component links chunk modules - show only changed entries

---

packages/utils/src/config/file-types.js

fix(utils): FileTypes - add missing extensions

---

packages/utils/src/config/file-types.js

rel: https://github.com/relative-ci/bundle-stats/issues/2108

fix(utils): FileTypes - add apng, m4a, aac,oga,wav,aac

---

packages/ui/src/components/summary-item/summary-item.module.css
packages/ui/src/components/summary/summary.jsx
packages/ui/src/components/summary/summary.module.css
packages/ui/src/css/variables.css

- enhance(ui): Increase text contrast
- enhance(ui): Summary - isolate metric items

enhance ui

---

package-lock.json
packages/plugin-webpack-filter/package.json
packages/plugin-webpack-filter/src/index.ts
packages/utils/src/constants.ts
packages/utils/src/webpack/extract/assets.ts
packages/utils/src/webpack/extract/modules-packages.ts
packages/utils/src/webpack/extract/modules.ts
packages/utils/src/webpack/index.js
packages/utils/src/webpack/types.ts

- fix(plugin-webpack-filter): Export types
- refactor(plugin-webpack-filter): Use internal types

Share filtered types

---

package-lock.json
packages/cli/package.json
packages/cli/src/run.ts

rel: https://github.com/relative-ci/bundle-stats/issues/2179

refactor(cli): Use listr2

---

packages/html-templates/build/storybook/preview.js
packages/ui/src/ui/filters/filters.jsx
packages/ui/src/ui/filters/filters.module.css

- build(html-templates): Add support for preact devtools on storybook
- fix(ui): Filters - toggle based on value
- fix(ui): Filters - limit items height to 10

fix filters

---

packages/utils/src/utils/component-links.js

close: https://github.com/relative-ci/bundle-stats/issues/1901

fix(utils): Modules filtered by chunk link - show all entries

---

packages/ui/src/components/bundle-assets/bundle-assets.jsx
packages/ui/src/components/bundle-assets/bundle-assets.utils.js
packages/utils/src/config/component-links.js
packages/utils/src/utils/component-links.js

close: https://github.com/relative-ci/bundle-stats/issues/1223

fix: Rename asset.asset to asset.other

---

packages/ui/src/components/metric/metric.jsx
packages/ui/src/components/metric/metric.module.css
packages/ui/src/components/summary-item/summary-item.jsx
packages/ui/src/components/summary-item/summary-item.module.css
packages/ui/src/ui/dropdown/dropdown.module.css
packages/ui/src/ui/filters/filters.jsx
packages/ui/src/ui/filters/filters.module.css
packages/ui/src/ui/hover-card/hover-card.jsx
packages/ui/src/ui/sort-dropdown/sort-dropdown.jsx
packages/ui/src/ui/sort-dropdown/sort-dropdown.module.css

- enhance(ui): Metric - updates
- enhance(ui): SummaryItem - tweak Metric usage

ui enhancements

---

packages/ui/src/components/summary-item/summary-item.jsx
packages/ui/src/ui/skeleton/skeleton.jsx
packages/ui/src/ui/skeleton/skeleton.module.css
packages/ui/src/ui/skeleton/skeleton.stories.jsx

- enhance(ui): Skeleton updates - rely on the wrapper display mode - adjust text mode background - add block variation
- fix(ui): SummaryItem - add skeleton wrappers

Enhance skeleton component

---

package-lock.json
packages/plugin-webpack-validate/package-lock.json
packages/plugin-webpack-validate/package.json
packages/plugin-webpack-validate/src/index.ts

close: https://github.com/relative-ci/bundle-stats/issues/2747

feat(plugin-webpack-validate): Log failed structure

---

packages/ui/src/components/metrics-table-options/metrics-table-options.jsx
packages/ui/src/components/summary-item/summary-item.jsx
packages/ui/src/css/default.css
packages/ui/src/css/variables.css
packages/ui/src/ui/dropdown/dropdown.jsx
packages/ui/src/ui/dropdown/dropdown.module.css
packages/ui/src/ui/dropdown/dropdown.stories.jsx
packages/ui/src/ui/empty-set/empty-set.jsx
packages/ui/src/ui/filters/filters.module.css
packages/ui/src/ui/hover-card/hover-card.module.css
packages/ui/src/ui/input/input.module.css
packages/ui/src/ui/sort-dropdown/sort-dropdown.jsx
packages/ui/src/ui/tooltip/tooltip.module.css

- fix(ui): Dropdown - ui tweaks
- fix(ui): Consistent shadow for focus/active states
- fix(ui): Default - remove obsoletes
- fix(ui): SummaryItem - decrease vertical spacing

fix dropdown component

---

packages/ui/src/ui/hover-card/hover-card.jsx

not closing on mouseleave on preact

fix(ui): HoverCard - revert hook

---

packages/ui/src/components/bundle-modules/index.jsx
packages/ui/src/components/metrics-table/index.js
packages/ui/src/components/metrics-table/index.jsx
packages/ui/src/components/metrics-table/metrics-table.jsx
packages/ui/src/components/metrics-table/metrics-table.module.css
packages/ui/src/hooks/search-params.js

rel: https://github.com/relative-ci/bundle-stats/issues/3009

Optimize large metrics table

---

package-lock.json
packages/cli-utils/package.json
packages/cli-utils/src/baseline.ts
packages/cli-utils/src/create-artifacts.ts
packages/cli-utils/src/index.ts
packages/cli-utils/src/reports.ts
packages/webpack-plugin/locales.json
packages/webpack-plugin/package.json
packages/webpack-plugin/src/config.js
packages/webpack-plugin/src/webpack-plugin.js
packages/webpack-plugin/typings.d.ts

Do not embed raw data into the html report

---

packages/ui/src/components/duplicate-packages-insight/duplicate-packages-insight.tsx
packages/utils/src/utils/component-links.ts

rel: https://github.com/relative-ci/bundle-stats/issues/2831

feat(ui): Duplicate packages insight - link to changed duplicate packages

---

packages/ui/src/components/insights/insights.stories.tsx
packages/utils/src/constants.ts
packages/utils/src/jobs/__tests__/__snapshots__/create-job.ts.snap
packages/utils/src/report/__tests__/__snapshots__/create.ts.snap
packages/utils/src/webpack/extract/__tests__/modules-packages-duplicate.ts
packages/utils/src/webpack/extract/__tests__/modules-packages-new-insight.ts
packages/utils/src/webpack/extract/modules-packages-duplicate.ts
packages/utils/src/webpack/extract/modules-packages-new-insight.ts

This reverts commit 8b757d75c6728aa8fb7cbea0016bb15ce309bd04.

Revert "feat(utils): Utils - add insight changes flag"

---

packages/ui/src/components/insight-icon/insight-icon.module.css
packages/ui/src/css/variables.css

- fix(ui): InsightIcon - improve warning contrast
- fix(ui): Improve gray color scheme

tweak color scheme

---

packages/ui/src/components/metrics-table-title/metrics-table-title.jsx
packages/ui/src/components/metrics-table-title/metrics-table-title.module.css
packages/ui/src/components/metrics-table/metrics-table.jsx
packages/ui/src/components/metrics-table/metrics-table.module.css
packages/ui/src/components/metrics-table/metrics-table.stories.jsx

- enhance(ui): MetricsTable - improve totals header
- enhance(ui): MetricsTable - show abs delta column
- refactor(ui): MetricsTable - inline headers
- fix(ui): MetricsTable - remove obsolete custom header props
- fix(ui): MetricTableTitle - consistent info styling & spacing

UI: Enhance metrics table

---

packages/html-templates/package-lock.json
packages/html-templates/package.json

Reverts relative-ci/bundle-stats#3619

Revert "build(deps-dev): bump preact from 10.10.6 to 10.16.0"

---

packages/ui/src/components/bundle-assets/bundle-assets.jsx
packages/ui/src/components/bundle-modules/bundle-modules.jsx
packages/ui/src/components/bundle-modules/bundle-modules.utils.js
packages/ui/src/components/bundle-modules/index.jsx
packages/ui/src/components/bundle-packages/bundle-packages.jsx

- fix(ui): Asset/Module/Package metric table - safe read the selected item
- fix(ui): BundleModules - filter by chunkId after merge

Fix BundleModules filters

---

.eslintrc.js
package-lock.json
packages/cli-utils/package.json
packages/cli-utils/src/fs.ts
packages/cli-utils/src/index.ts
packages/cli/package.json
packages/cli/src/run.ts

close: https://github.com/relative-ci/bundle-stats/issues/3425

Move async JSON  read stream to cli-utils

---

packages/ui/src/ui/dropdown/dropdown.module.css
packages/ui/src/ui/filters/filters.module.css

- fix(utils): Report - set run to empty values to flag removed entries
- enhance(ui): Dropdown - add space between items
- enhance(ui): Filters dropdown - improve only button

enhance dropdowns

---

packages/cli-utils/src/reports.ts
packages/webpack-plugin/src/webpack-plugin.js

resolves: https://github.com/relative-ci/bundle-stats/issues/3843

Fix BUNDLE_STATS_BASELINE env value

---

package-lock.json

This reverts commit 107b14a8694e0c425234cfde7999676715e2767e.

Revert "build(deps-dev): bump @types/fs-extra from 11.0.1 to 11.0.2"

---

packages/ui/src/app/app.module.css
packages/ui/src/components/run-info/run-info.module.css

- fix(ui): RunInfo - adjust icon position and states
- fix(ui): App - fix tabs border

fix report ui

---

packages/utils/src/webpack/metrics.ts

- fix(ui): Webpack metrics - set regression for duplicate modules
- fix(ui): Webpack metrics - update descriptions

fix metric regression config

---

packages/ui/src/i18n.js
packages/utils/src/webpack/metrics.ts

- fix(ui): Webpack metrics - set regression for duplicate modules
- fix(ui): Webpack metrics - update descriptions
- fix(ui): App - generic bundler titles

update metric info

---

README.md

doc: README - fix demo URLs

---

packages/utils/src/jobs/__tests__/__snapshots__/create-job.ts.snap
packages/utils/src/report/__tests__/__snapshots__/add-row-metric-data.ts.snap
packages/utils/src/report/__tests__/__snapshots__/create.ts.snap
packages/utils/src/utils/metrics.ts
packages/utils/src/webpack/__tests__/__snapshots__/compare.js.snap

- fix(utils): RunInfo -  do not include undefined regression
- DROP: v4.7.6-beta.0

fix get metric run

---

packages/plugin-webpack-filter/src/index.ts
packages/utils/__fixtures__/webpack-stats-1.extracted.js
packages/utils/src/jobs/__tests__/__snapshots__/create-job.ts.snap

fix(filter): Skip modules that do not belong to any chunk

---

packages/ui/src/components/bundle-modules/bundle-modules.jsx
packages/ui/src/components/bundle-modules/bundle-modules.utils.js

- style(ui): Bundle modules utils - fix formatting
- perf(ui): BundleModules - move chunks processing on closure
- perf(ui): BundleModules - do not use destructuring for chunks filters

Fix bundle modules filter performance

---

package-lock.json
packages/html-templates/package.json

This reverts commit 16d0431ebb01d7118aa703d3d070a573db6315d7.

Revert "build(deps-dev): bump preact from 10.18.1 to 10.18.2"

---

packages/utils/src/webpack/__tests__/utils-get-asset-name.ts
packages/utils/src/webpack/utils.ts

- rel: https://github.com/relative-ci/bundle-stats/issues/3921

fix(utils): Webpack utils - add support for base64URL hash

---

packages/utils/src/webpack/__tests__/utils-get-asset-name.ts
packages/utils/src/webpack/utils.ts

- rel: https://github.com/relative-ci/bundle-stats/issues/3921

fix(utils): Asset name - add support for tilde separator

---

.github/workflows/ci.yml

- build(deps): bump actions/upload-artifact from 3 to 4
- build(deps): bump actions/download-artifact from 3 to 4

chore: Update artifact actions

---

packages/ui/src/css/variables.css
packages/ui/src/ui/button/button.module.css
packages/ui/src/ui/button/button.tsx

- improve(ui): Color scheme - improve yellow contrast
- improve(ui): Button - improve outline + kind/radius

ui improvements

---

packages/ui/src/components/sort-button/sort-button.tsx

resolves: https://github.com/relative-ci/bundle-stats/issues/4172

fix(ui): SortButton - wrap Tooltip in Button

---

packages/ui/src/components/bundle-assets-totals/bundle-assets-totals.jsx

rel: https://github.com/relative-ci/bundle-stats/pull/4196

fix(ui): BundleAssetsTotals - allow to pass a different onClick fn

---

packages/ui/src/components/metrics-treemap/metrics-treemap.module.css
packages/ui/src/components/metrics-treemap/metrics-treemap.tsx

- fix(ui): Treemap - prevent tooltip content from capturing user mouse hover
- perf(ui): Treemap - remove wrappers

improve treemap

---

packages/ui/src/components/bundle-assets-totals/bundle-assets-totals.jsx
packages/ui/src/components/metrics-treemap/__tests__/metrics-treemap.utils.ts
packages/ui/src/components/metrics-treemap/metrics-treemap.constants.ts
packages/ui/src/components/metrics-treemap/metrics-treemap.i18n.ts
packages/ui/src/components/metrics-treemap/metrics-treemap.module.css
packages/ui/src/components/metrics-treemap/metrics-treemap.tsx
packages/ui/src/components/metrics-treemap/metrics-treemap.utils.ts

- enhance(ui): TreemapMetrics - increase tile bacground contrast
- feat(ui): TreemapMetrics - calculate and show nested group totals

TreemapMetrics improvements

---

packages/ui/src/components/metrics-treemap/metrics-treemap.constants.ts
packages/ui/src/components/metrics-treemap/metrics-treemap.module.css
packages/ui/src/components/metrics-treemap/metrics-treemap.tsx
packages/ui/src/components/metrics-treemap/metrics-treemap.utils.ts

resolves https://github.com/relative-ci/bundle-stats/issues/4456

MetricsTreemap - tile group tooltip

---

packages/ui/src/components/bundle-assets/bundle-assets.jsx
packages/ui/src/components/bundle-modules/bundle-modules.tsx
packages/ui/src/components/bundle-packages/bundle-packages.jsx
packages/ui/src/components/metrics-treemap/metrics-treemap.module.css
packages/ui/src/components/metrics-treemap/metrics-treemap.tsx

- fix(ui): MetricsTreemap - show runInfo only the data is available
- fix(ui): MetricsTreemap - add missing titles
- fix(ui): MetricsTreemap - increase background contrast

Tweak treemap UI

---

packages/ui/src/components/module-info/module-info.tsx

resolves: https://github.com/relative-ci/bundle-stats/issues/4636

fix(ui): ModuleInfo - handle missing baseline

---

packages/ui/src/components/module-info/module-info.tsx

- resolves: https://github.com/relative-ci/bundle-stats/issues/4639

fix(ui): ModuleInfo - skip diff when baseline is missing

---

packages/utils/src/config/component-links.js
packages/utils/src/utils/component-links.ts

- resolves https://github.com/relative-ci/bundle-stats/issues/4296

feat(utils): Module links - show duplicateSize when viewing duplicate modules

---

packages/ui/src/css/variables.css
packages/ui/src/ui/dialog/dialog.module.css
packages/ui/src/ui/dialog/dialog.stories.tsx
packages/ui/src/ui/hover-card/hover-card.module.css
packages/ui/src/ui/tooltip/tooltip.stories.module.css
packages/ui/src/ui/tooltip/tooltip.stories.tsx

- **enhance(ui): Variables - increase shadow color contrast**
- **fix(ui): HoverCard - equal padding**
- **fix(ui): Dialog - adjust width variation**
- **test(ui): Tooltip - add custom tooltip case**

Improve overlays
