relative-ci/bundle-stats

- packages/webpack-plugin/README.md
Looks like we shouldn't install `bundle-stats` but should install `bundle-stats-webpack-plugin`. Have a nice day!
> docs: adjust pkg name to install

- packages/utils/src/webpack/extract/__tests__/assets.js
- packages/utils/src/webpack/extract/assets.js
Removes the query from the file name. Allows for files name :
72589901332095ed3ff1.theme.css?sha384 -> 72589901332095ed3ff1.theme.css
theme.72589901332095ed3ff1.css?sha384 -> theme.css
main.72589901332095ed3ff1.bundle.js?sha384 -> main.bundle.js
fixed #1164
> Support files that have a query in the file name.

- packages/webpack-plugin/README.md
- packages/webpack-plugin/src/webpack-plugin.js
Relate to [Feature Request for webpack plugin : new option to disable bundle-stats logger](https://github.com/relative-ci/bundle-stats/issues/1256)
> feat: add an option to only log error/warning and stop logging info

- packages/webpack-plugin/typings.d.ts
Webpack requires for plugins to implement the apply `apply(compiler)` method.
bundle-stats does have that method implemented in `webpack-plugin.js` but the method is missing in `typing.d.ts` declaration file.
As a result, the attempt to use `bundle-stats` in the following way will fail and will show TS errors.
```
import { BundleStatsWebpackPlugin } from 'bundle-stats-webpack-plugin';
....
plugins: [
new BundleStatsWebpackPlugin({ ... }),
...
]
```
Currently, trying to use bundle-stats in the following manner will throw an error saying `Property 'apply' is missing in type 'BundleStatsWebpackPlugin' but required in type 'WebpackPluginInstance'.`
> adding apply method to BundleStatsWebpackPlugin to plugin typings.d.ts

- fixtures/job.baseline.json
- fixtures/job.current.json
- packages/cli-utils/__fixtures__/webpack-stats-baseline.json
- packages/cli-utils/__fixtures__/webpack-stats-current.json
- packages/cli/README.md
- packages/cli/__fixtures__/webpack-stats-baseline.json
- packages/cli/__fixtures__/webpack-stats-current.json
- packages/plugin-webpack-filter/src/index.ts
- packages/utils/__fixtures__/webpack-stats-1.extracted.js
- packages/utils/__fixtures__/webpack-stats-1.js
- packages/utils/__fixtures__/webpack-stats-2.extracted.js
- packages/utils/__fixtures__/webpack-stats-2.js
- packages/utils/__fixtures__/webpack-stats-3.extracted.js
- packages/utils/__fixtures__/webpack-stats-3.js
- packages/utils/src/jobs/__tests__/__snapshots__/create-job.js.snap
- packages/utils/src/webpack/extract/__tests__/assets.ts
- packages/utils/src/webpack/extract/assets.ts
- packages/webpack-plugin/README.md
- packages/webpack-plugin/__fixtures__/webpack-stats-baseline.json
- packages/webpack-plugin/__fixtures__/webpack-stats-current.json
- packages/webpack-plugin/src/webpack-plugin.js
- packages/webpack-plugin/typings.d.ts
BREAKING: Skip extracting .entrypoints data
close: https://github.com/relative-ci/bundle-stats/issues/2179
> feat: Base asset.isEntry on chunks[].entry

- packages/ui/src/components/bundle-modules/bundle-modules.utils.js
- packages/webpack-plugin/src/webpack-plugin.js
- fix(ui): BundleModules -  prevent error when comparing with an empty job
- fix(webpack-plugin): Skip compare mode if baseline is missing
> Fix empty baseline

- packages/ui/src/components/bundle-modules/bundle-modules.utils.js
- fix(ui): BundleModules -  prevent error when comparing with an empty job
- fix(webpack-plugin): Skip compare mode if baseline is missing
- fix(ui): BundleModules - skip filtering when job modules are empty
> fix empty modules

- packages/ui/src/components/bundle-assets/bundle-assets.utils.js
- packages/ui/src/components/bundle-modules/bundle-modules.utils.js
- packages/ui/src/components/bundle-packages/bundle-packages.utils.js
Instead of using %.
Sorting by % change isn't useful when files (packages / modules / assets) are all different sizes. Instead, let's sort by the actual delta in bytes.
Closes #2980
> Order By Delta: use literal byte delta

- package-lock.json
- packages/cli-utils/package.json
- packages/cli-utils/src/baseline.ts
- packages/cli-utils/src/reports.ts
- packages/cli/README.md
- packages/cli/src/cli.ts
- packages/cli/src/run.ts
- packages/cli/test/package/cli.test.js
- packages/webpack-plugin/README.md
- packages/webpack-plugin/src/__tests__/webpack-plugin.test.js
- packages/webpack-plugin/src/webpack-plugin.js
- packages/webpack-plugin/typings.d.ts
- rel https://github.com/relative-ci/bundle-stats/issues/801
> feat: Custom baseline filepath

- packages/webpack-plugin/src/webpack-plugin.js
It seems like the options object supplied to `next-plugin-bundle-stats` isn't being propagated in the calls to `generateReports`. This PR adds that.
> Add webpack plugin config bundle propagation

- package-lock.json
- packages/ui/package.json
- packages/ui/src/app/app.jsx
- packages/ui/src/query-state.jsx
- packages/ui/src/query-state.tsx
- packages/utils/src/utils/__tests__/component-links.ts
- packages/utils/src/utils/component-links.ts
Mixed strategy to encode the component state into the URL with a smaller size 
| | Before | After |
|---|---|---|
| ~600 chunks | `16k` | `6K` |
rel: https://github.com/relative-ci/bundle-stats/issues/3946
> Update query string encoding

- packages/utils/src/webpack/extract/__tests__/assets.ts
- packages/utils/src/webpack/extract/assets.ts
resolves: https://github.com/relative-ci/bundle-stats/issues/4037
> fix(utils): Extract assets - prevent  asset name collision

- packages/cli/README.md
- packages/rollup-plugin/README.md
- packages/webpack-plugin/README.md
> doc: Add output/config guides

- packages/ui/src/components/metrics-table/metrics-table.i18n.ts
- packages/ui/src/components/metrics-table/metrics-table.tsx
- packages/ui/src/hooks/rows-sort.ts
resolves: https://github.com/relative-ci/bundle-stats/issues/4119
> fix(ui): MetricsTable - sort by actual value

- packages/ui/src/ui/button/button.module.css
- packages/ui/src/ui/button/button.tsx
- packages/ui/src/ui/dropdown/dropdown.jsx
- packages/ui/src/ui/dropdown/dropdown.module.css
- fix(ui): Button - add support for custom element types
- fix(ui): Button - outline + padding variation
- fix(ui): Dropdown - use button component
> fix buttons

- packages/ui/src/ui/dropdown/dropdown.jsx
- packages/ui/src/ui/dropdown/dropdown.module.css
This reverts commit e8e3cae14dfa7d5e4de14af6491bc7e7703f82f9.
> Revert "fix(ui): Dropdown - use button component"

- packages/utils/src/webpack/__tests__/utils-get-asset-name.ts
- packages/utils/src/webpack/utils.ts
- feat(utils): Asset names - extract hash from nextjs manifest paths
- fix(utils: Asset names - output hashed directory
> Nextjs - add support for manifest asset names

- packages/utils/src/webpack/extract/__tests__/modules-packages.ts
- packages/utils/src/webpack/extract/modules-packages.ts
resolves: https://github.com/relative-ci/bundle-stats/issues/4285
> fix(utils): Extract package - skip module federation modules

- packages/ui/src/components/module-info/module-info.tsx
The index in the array of jobs isn't the number!
Before this change the `Job #1` and `Job #2` were reversed.
Turns out, everywhere else we reference the jobs we always look up the label in the labels map. That wasn't being done here and thus the jobs were actually mis-labeled (2 was 1 and 1 was 2) making the chunk list in module-info attributed to the wrong job.
Now it's fixed and the right job labels are show.
Here's an example of the bug (notice the different ordering in the jobs):
> module-info: fix reversed job names!

- packages/ui/src/components/bundle-assets/bundle-assets.jsx
- packages/ui/src/components/bundle-modules/bundle-modules.tsx
- packages/ui/src/components/bundle-packages/bundle-packages.jsx
- packages/ui/src/components/metrics-treemap/metrics-treemap.module.css
- packages/ui/src/components/metrics-treemap/metrics-treemap.tsx
- group tile hover 
- group tile click toggler
- improve tile size detection
rel: https://github.com/relative-ci/bundle-stats/issues/623
> MetricsTreemap improvements

- packages/ui/src/components/metrics-treemap/metrics-treemap.constants.ts
- packages/ui/src/components/metrics-treemap/metrics-treemap.tsx
- packages/ui/src/components/metrics-treemap/metrics-treemap.utils.ts
- fix(ui): MetricsTreemap - do not show group tile delta on single run
> fix metrics treemap single run

- packages/webpack-plugin/README.md
- rel: https://github.com/relative-ci/bundle-stats/issues/4505
> doc(webpack-plugin): How to exclude virtual modules

- packages/ui/src/components/bundle-modules/bundle-modules.constants.ts
- packages/ui/src/components/bundle-modules/bundle-modules.tsx
- packages/ui/src/components/bundle-modules/index.tsx
- packages/utils/src/webpack/compare.ts
- packages/utils/src/webpack/selectors.js
rel: https://github.com/relative-ci/bundle-stats/issues/4300
> Modules duplicate size view

- packages/plugin-webpack-filter/package.json
resolves: https://github.com/relative-ci/bundle-stats/issues/4630
> Fix ESM exports

- packages/ui/src/components/bundle-modules/bundle-modules.utils.ts
- packages/utils/src/webpack/selectors.js
- resolves https://github.com/relative-ci/bundle-stats/issues/4301#issuecomment-2297390549
> Fix module duplicate size'

- packages/ui/src/components/bundle-modules/bundle-modules.tsx
- rel: https://github.com/relative-ci/bundle-stats/issues/4823
> fix(ui): BundleModules - do not clear metric when opening side info
